[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.29"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
zksync_sepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
